import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
shop=driver.find_element_by_id("menu-item-40")
shop.click()
driver.execute_script("window.scrollBy(0, 300);")
Book1 = driver.find_element_by_xpath("//a[@href='/shop/?add-to-cart=181']")
Book1.click()
time.sleep(3)
Basket = driver.find_element_by_xpath("//a[@title='View Basket']")
Basket.click()
time.sleep(3)
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
checkout = WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//a[@href='http://practice.automationtesting.in/checkout/']")) )
checkout.click()
first_name = WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.ID, "billing_first_name")) )
first_name.send_keys("Ruslan")
last_name = driver.find_element_by_id("billing_last_name")
last_name.send_keys("Butenko")
reg_mail = driver.find_element_by_id("billing_email")
reg_mail.send_keys("Ruslapan@mail.ru")
phone = driver.find_element_by_id("billing_phone")
phone.send_keys("78933455799")
country = driver.find_element_by_class_name("select2-container")
country.click()
input_country = driver.find_element_by_class_name("select2-input")
input_country.click()
input_country.send_keys("Germany")
input_country2 = driver.find_element_by_id("select2-results-1")
input_country2.click()
time.sleep(3)
address = driver.find_element_by_xpath("//input[@name='billing_address_1']")
address.send_keys("Ланквиц")
postcode = driver.find_element_by_xpath("//input[@name='billing_postcode']")
postcode.send_keys("12247")
town = driver.find_element_by_xpath("//input[@name='billing_city']")
town.send_keys("Berlin")
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(3)
check = driver.find_element_by_xpath("//input[@value='cheque']")
check.click()
place_order = driver.find_element_by_id("place_order")
place_order.click()
title1 = WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.CLASS_NAME,"woocommerce-thankyou-order-received"), "Thank you. Your order has been received."))
print(title1)
title2 = WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.CLASS_NAME,"method"), "Check Payments"))
print(title2)
driver.quit()
